name: jolideco-gmm-library

channels:
  - conda-forge

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - python=3.9
  - scikit-image
  - scikit-learn
  - scipy
  - astropy=5.2
  - numpy
  - matplotlib
  - gammapy=1.0
  - yaml
  - requests
  - tqdm
  - jupyter