name: nrao-jets-isotropic-v0.1
pre-process-script: preprocess.py
filename: gmm-nrao-jets-isotropic-v0.1.fits.gz
format: table
extract-patches:
    input-images: images/*.fits.gz
    patch-shape: [8, 8]
    stride: 1
    random-rotation: true
    filename: patches/patches-nrao-jets-isotropic-v0.1.fits.gz
    gaussian-smoothing: 1.
    downsample-block-size: [2, 1]
sklearn-gmm-kwargs:
    n_components: 64
    warm_start: False
    covariance_type: full
    n_init: 1
    tol: 0.001
    max_iter: 200
    init_params: 'kmeans'
plots:
    ncols: 8

