name: nrao-jets-v0.1
preprocess-script: make.py
filename: gmm-nrao-jets-v0.1.fits
format: table
learn-gmm:
  input-images: images/*.fits
  patch-shape: (8, 8)
  sklearn-gmm-kwargs:
      n_components: 32
      warm_start: False
      covariance_type: full
      n_init: 1

